# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WfNzhoORWeb3Eqe-R54sQILMH4hjDJgs
"""

first=2
second=4
print(first+second)
print(first-second)
print(first*second)
print(first/second)
print(first%second)
print(first**second)
print(first//second)

